[package]
name = "tetris"
version = "0.0.1"
authors = ["Santiago Bandiera <sagaban@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"

[features]
default = ["sdl2/image"]
